# Generated by Django 2.2 on 2019-07-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('estimated_count', models.IntegerField(verbose_name='good for how many people')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('custumer_name', models.CharField(max_length=100)),
                ('custumer_id_no', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('amount', models.FloatField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.Dish')),
            ],
        ),
    ]
