# Generated by Django 2.2 on 2019-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
