# Generated by Django 2.2 on 2019-07-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='photo',
        ),
    ]
