# Generated by Django 2.2.4 on 2019-11-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_remove_order_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='everyday',
            field=models.BooleanField(default=False),
        ),
    ]
