# Generated by Django 2.2 on 2019-07-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_dish_sold_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custumer_id_no',
            new_name='id_no',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='custumer_name',
            new_name='name',
        ),
    ]
