# Generated by Django 2.2.4 on 2019-12-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_dish_everyday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
