# Generated by Django 2.2 on 2019-07-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0004_auto_20190725_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='estimated_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(default="It's so yummy, you might forget your name."),
        ),
    ]
