# Generated by Django 2.2.4 on 2020-01-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0005_auto_20191201_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
