# Generated by Django 2.2 on 2019-07-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0006_auto_20190726_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.CharField(max_length=101),
        ),
    ]
