# Generated by Django 2.2 on 2019-07-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0007_auto_20190726_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='served',
            field=models.BooleanField(default=False),
        ),
    ]
