# Generated by Django 2.2 on 2019-07-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0009_order_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_no',
            field=models.IntegerField(verbose_name='contact no.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_no',
            field=models.CharField(max_length=100, verbose_name='id no.'),
        ),
    ]
