# Generated by Django 2.2.8 on 2020-02-03 09:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0009_auto_20200203_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=0, size=[400, 400], upload_to=''),
        ),
    ]
