# Generated by Django 2.2.8 on 2020-02-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0011_auto_20200203_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact_no',
            field=models.CharField(max_length=12),
        ),
    ]
