# Generated by Django 2.2 on 2019-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0013_auto_20190731_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.ImageField(default='', upload_to='dishes'),
            preserve_default=False,
        ),
    ]
