# Generated by Django 2.2 on 2019-07-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0018_auto_20190731_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
