# Generated by Django 2.2 on 2019-07-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0021_auto_20190731_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
